#ifndef _GAME_ACTOR_INCLUDE
#define _GAME_ACTOR_INCLUDE
#include "Sprite.h"

enum PlayerState {
	STANDING_LEFT, STANDING_RIGHT, RUNING_LEFT, RUNING_RIGHT, WALKING_LEFT, WALKING_RIGHT, JUMPING_LEFT, JUMPING_RIGHT, FALLING_RIGHT, FALLING_LEFT,
	JUMP_STANDING_LEFT, JUMP_STANDING_RIGHT, TURNING_LEFT, TURNING_RIGHT, STOPING_RIGHT, STOPING_LEFT, DOWNING_RIGHT, DOWNING_LEFT,
	TURN_RUNING_RIGHT, TURN_RUNING_LEFT, PRE_JUMPING_RIGHT, PRE_JUMPING_LEFT, PRE_RUNING_RIGHT, PRE_RUNING_LEFT, GRABING_RIGHT, GRABING_LEFT, CLIMBING_LEFT,
	CLIMBING_RIGHT, CLIMBING_LEFT_DOWN, CLIMBING_RIGHT_DOWN, SWORDING_OUT_RIGHT, SWORDING_OUT_LEFT, SWORD_STANDING_RIGHT, SWORD_STANDING_LEFT,
	SWORDING_IN_RIGHT, SWORDING_IN_LEFT, SWORD_ATTACKING_RIGHT, SWORD_ATTACKING_LEFT, PARRYING_RIGHT, PARRYING_LEFT, SWORD_STEPING_F_RIGHT, SWORD_STEPING_F_LEFT,
	SWORD_STEPING_B_RIGHT, SWORD_STEPING_B_LEFT, DRINKING_RIGHT, DRINKING_LEFT, PRE_JUMPING_LEFT2, PRE_JUMPING_RIGHT2, JUMPING_RIGHT2, JUMPING_LEFT2, 
	POST_JUMPING_RIGHT2, POST_JUMPING_LEFT2
};

class GameActor
{
public:
	Sprite* getSprite();
	int health;
	int max_health;
	bool down_key;
	glm::ivec2 size;
	glm::ivec2 position_col;
	glm::ivec2 old_position_col;
	float magic = 16.0f;
	float speed = 2.0f;
	bool alive;
	PlayerState state;

	virtual void drink();
protected:
	
	Sprite *sprite;
};

#endif // _GAME_ACTOR_INCLUDE